const COLOR_PRIMARY = "#051A8B";
const COLOR_ACCENT = "#FE7C01";
const COLOR_RED = "#ff0000";
const COLOR_GREY = "#9B9B9B";
const COLOR_GREEN = "#00f000";

export { COLOR_PRIMARY, COLOR_ACCENT, COLOR_RED, COLOR_GREY, COLOR_GREEN };
